// English resources
export const en = {
  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    loading: 'Loading...',
    processing: 'Processing...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    version: 'Version',
    file: 'File',
    folder: 'Folder',
    open: 'Open',
    export: 'Export',
  },

  // Application
  app: {
    title: 'Forguncy Analyzer Pro',
    subtitle: 'Analyze Forguncy projects and auto-generate specifications & review reports',
    footer: 'Powered by HarmonicInsight',
  },

  // File selection
  fileSelect: {
    dropzone: 'Drop project file here',
    orClick: 'or click to select',
    supportedFormat: 'Supported format: .fgcp (Forguncy project file)',
    selected: 'Selected file',
    changeFile: 'Click or drop to change',
  },

  // Analysis options
  options: {
    title: 'Analysis Options',
    generateSpec: 'Specification Generation',
    generateSpecDesc: 'Generate detailed specification in Word format',
    codeReview: 'Code Review',
    codeReviewDesc: 'Detect security and bug risks',
    orgAnalysis: 'Organization Analysis',
    orgAnalysisDesc: 'Identify areas affected by personnel changes',
    fixGuide: 'Fix Guide',
    fixGuideDesc: 'Generate remediation instructions',
  },

  // Output settings
  output: {
    folder: 'Output Folder',
    notSet: 'Not set',
    change: 'Change',
    generatedFiles: 'Generated Files',
    openFolder: 'Open Output Folder',
  },

  // Analysis
  analysis: {
    start: 'Start Analysis',
    analyzing: 'Analyzing...',
    complete: 'Complete',
    results: 'Analysis Results',
    tables: 'Tables',
    pages: 'Pages',
    workflows: 'Workflows',
    serverCommands: 'Server Commands',
    columns: 'Columns',
    relations: 'Relations',
    buttons: 'Buttons',
    formulas: 'Formulas',
  },

  // Review
  review: {
    title: 'Code Review Report',
    issues: 'Detected Issues',
    summary: 'Summary',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    total: 'Total',
    category: {
      security: 'Security',
      bug: 'Bug Risk',
      performance: 'Performance',
      maintainability: 'Maintainability',
      workflow: 'Workflow',
      organization: 'Organization',
    },
    location: 'Location',
    suggestion: 'Recommendation',
  },

  // License
  license: {
    title: 'License',
    currentTier: 'Current Plan',
    free: 'Free',
    trial: 'Trial',
    standard: 'Standard',
    professional: 'Professional',
    enterprise: 'Enterprise',
    expiresAt: 'Expires',
    unlimited: 'Unlimited',
    activate: 'Activate',
    enterKey: 'Enter license key',
    invalidKey: 'Invalid license key',
    expired: 'License has expired',
    activated: 'License activated',
    upgrade: 'Upgrade',
    upgradeCta: 'Available with upgrade',
    purchaseUrl: 'Open Purchase Page',
    deactivate: 'Deactivate',
    generateTestKey: 'Generate Test Key',
    devTools: 'Developer Tools',
    restrictions: 'Feature Restrictions',
    maxProjects: 'Max Projects',
    maxTables: 'Max Tables',
    maxPages: 'Max Pages',
  },

  // Progress
  progress: {
    reading: 'Reading project file...',
    analyzingTables: 'Analyzing table definitions...',
    analyzingPages: 'Analyzing page definitions...',
    analyzingWorkflows: 'Analyzing workflows...',
    analyzingCommands: 'Analyzing server commands...',
    reviewing: 'Running code review...',
    generatingSpec: 'Generating specification...',
    generatingReport: 'Generating review report...',
    complete: 'Complete',
  },

  // Errors
  errors: {
    fileNotFound: 'File not found',
    invalidFile: 'Invalid file format',
    analysisError: 'Error occurred during analysis',
    exportError: 'Error occurred during export',
    networkError: 'Network error occurred',
    unknownError: 'Unexpected error occurred',
    licenseRequired: 'License required for this feature',
    limitExceeded: 'Limit exceeded',
  },

  // Specification
  spec: {
    title: 'System Specification',
    generatedBy: 'Auto-generated by Forguncy Analyzer Pro',
    generatedAt: 'Generated at',
    toc: 'Table of Contents',
    overview: 'System Overview',
    projectOverview: 'Project Overview',
    tableDefinition: 'Table Definitions',
    tableList: 'Table List',
    tableDetail: 'Table Details',
    columnName: 'Column Name',
    dataType: 'Data Type',
    required: 'Required',
    unique: 'Unique',
    defaultValue: 'Default Value',
    pageList: 'Page List',
    pageDetail: 'Page Details',
    workflowDefinition: 'Workflow Definitions',
    stateList: 'State List',
    transitionList: 'Transition List',
    serverCommandList: 'Server Command List',
    erDiagram: 'ER Diagram (Mermaid)',
  },
};
